# Generated by Django 5.2 on 2025-04-27 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlorianApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='automovil',
            old_name='diseño',
            new_name='diseno',
        ),
        migrations.AlterField(
            model_name='automovil',
            name='marca',
            field=models.CharField(max_length=100),
        ),
    ]
